# Site settings
title: Your Blog Title
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: "http://example.com"

author:
  fullname: Anonymous
  github: njdehoog
  twitter: nielsify
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

theme:
  footer_text: >
   Lovingly baked with [Spelt](http://spelt.io)